---
title: "Zmienne PGSS"
output: 
  rmarkdown::html_vignette:
    toc: yes
vignette: >
  %\VignetteIndexEntry{Zmienne PGSS}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE, cache=FALSE}
library(dplyr)
requireNamespace("labelled")
data(pgss, package="adr")
knitr::opts_chunk$set(
  cache=FALSE,
  echo=FALSE
)
```


Krótki opis zmiennych PGSS w ramce `pgss`.

Dane pochodzą z Archiwum Danych Społecznych http://ads.org.pl.

```{r read-data, include=FALSE}
opisy <- pgss %>%
  mutate(across(- one_of("recordid", "pgssyear"), ~ !is.na(.))) %>%
  tidyr::pivot_longer(
    - one_of("recordid", "pgssyear"),
    names_to = "variable",
    values_to = "isna"
  ) %>%
  group_by(variable, pgssyear) %>%
  summarise( nna = sum(isna), .groups = "drop" ) %>%
  tidyr::pivot_wider(names_from = pgssyear, values_from = nna) %>%
  left_join(
    labelled::var_label(pgss) %>%
      unlist() %>%
      tibble::enframe(name = "variable", value = "label"),
    by = "variable"
  )
```


# Nazwy zmiennych i etykiety

```{r opisy-zmiennych}
o <- order(opisy$variable)
knitr::kable( 
  structure(
    opisy[o,c(1,11)], 
    names=c("Zmienna", "Opis")
    )
  )
```



# Kiedy zadawano pytanie

Poniżej można się zorientować kiedy zadano które pytania. W każdej komórce liczba respondentów, którzy udzielili znaczących odpowiedzi. Jeżeli jest 0, znaczy, że pytanie nie zostało zadane.

```{r}
knitr::kable(
  structure(
    opisy[,-11],
    names=replace(names(opisy)[-11], 1, "Zmienna")
  )
)
```
